### PR TITLE
Starting to verify laws

### PR DESCRIPTION
**Pull request by wallymathieu**

### CODE REVIEW

**Comment by gusty** [comment]
I see all green, which rules don't hold?

**Comment by wallymathieu** [comment]
Applicative:
`u <*> result y = result ((<|) y) <*> u`

Alternative:
`(f <|> g) <*> x = (f <*> x) <|> (g <*> x)`

`empty <*> f = empty`

**Comment by gusty** [comment]
I think FsCheck provides you with a counterexample when it fails, do have it?

**Comment by wallymathieu** [comment]
I'm having trouble coming up with types that compile for `u <*> result y = result ((<|) y) <*> u`.

Alternative: `(f <|> g) <*> x = (f <*> x) <|> (g <*> x)`
`(x=AccFailure [""], y=AccFailure [], f=AccFailure [], g=AccFailure [])`

Alternative: `empty <*> f = empty`
`f:AccValidation<string list,int->string> = AccFailure [""]`

**Comment by wallymathieu** [comment]
So perhaps it's me being confused?

**Comment by gusty** [comment]
For applicative you have the operator flipped in the rule, it should be ``|>`` :

    let u : AccValidation<string list,_> = AccSuccess ( (+) 1)
    let y =  10 

    let x1 =   u <*> result y 
    let x2 = result ((|>) y) <*> u
    x1 = x2

Regarding ``empty`` I'm in doubt if it's an Alternative with empty as there are more than a single value for ``empty``. Precisely these days I'm thinking about to add a "halfway concept" which has a method ``isEmpty`` instead, to be able to model these types more accurately.

**Comment by wallymathieu** [comment]
Aaa, thanks!

**Comment by gusty** [comment]
I see that you translated ``mempty`` from Haskell to ``empty``.
That's not exactly the same, ``mempty`` is from Haskel's monoid, here it's ``zero`` whereas ``empty`` is the same in both.

Anyway I'm still in doubt about the Monoid in the error branch. If the error is a semigroup then there is no monoid instance for it. But ok, that's not necessarily wrong, it could be a constrained monoid for the case where the error branch is more than a semigroup.

**Comment by gusty** [comment]
By the way, I read the Haskell docs and definitely ``Alt`` is to ``Alternative`` like ``Semigroup``  to ``Monoid`` it states clearly ``<!>`` is ``<|>`` without a required ``empty``.

We should add it in F#+ docs. But we don't need a separated operator, we can keep using ``<|>``.

**Comment by wallymathieu** [comment]
Where is the `<!>` defined?

**Comment by gusty** [comment]
In F#+ <!> has a different meaning. It’s an alias for map, which in Haskell is <$> but that’s an invalid operator in F#. 

So <!> belongs to Applicative, and it’s defined directly in operators.fs

**Pull request merged**
